### ISSUE TITLE
Missing ItemDrop in DevKacper.Mechanic

### ISSUE THREAD

**Issue by twinring** [KacperGra/Minecraft-2D#2]
@KacperGra 
Assets/Scripts/UI/Inventory/ItemDrop.cs(6,44): error CS0234: The type or namespace name 'ItemDrop' does not exist in the namespace 'DevKacper.Mechanic' (are you missing an assembly reference?)
Please help!

**Comment by KacperGra** [comment]
> @KacperGra Assets/Scripts/UI/Inventory/ItemDrop.cs(6,44): error CS0234: The type or namespace name 'ItemDrop' does not exist in the namespace 'DevKacper.Mechanic' (are you missing an assembly reference?) Please help!

Hi! I probably didn't send some files and it causes this error. I will send it later :)

**Comment by twinring** [comment]
Thank so much! I think the files are missing in:
https://github.com/KacperGra/DevKacper-Essentials

**Comment by KacperGra** [comment]
> Thank so much! I think the files are missing in: https://github.com/KacperGra/DevKacper-Essentials

Hi again. I send all files to main so you can download changes :)
